### ISSUE TITLE
[城市名] XXXX 公司诚聘 XX工程师 薪水 AAA-ZZZ RMB/USD

### ISSUE THREAD

**Issue by Colonel86** [rebase-network/who-is-hiring#161]
## 公司/团队介绍
北京星润时代网络科技有限公司

## 薪资福利待遇
35-50k

## 地点
- 办公地点燕郊

- 联系方式：
微信: 491545901

## 工作性质
- 全职/远程

## 岗位要求、职责
主要负责以太坊智能合约开发工作，要求有三年以上的开发经验
swap和农场及nft交易经验最好

招聘3位

**Comment by xrdavies** [comment]
> ## 公司/团队介绍
> 北京星润时代网络科技有限公司
> 
> ## 薪资福利待遇
> 35-50k
> 
> ## 地点
> * 办公地点燕郊
> * 联系方式：
>   微信: 491545901
> 
> ## 工作性质
> * 全职/远程
> 
> ## 岗位要求、职责
> 主要负责以太坊智能合约开发工作，要求有三年以上的开发经验 swap和农场及nft交易经验最好
> 
> 招聘3位
> 
> ## 工作环境

招聘信息太过简略的话小编那边可能没办法帮忙发布
