### ISSUE TITLE
[上海/远程/日本]SuicaSwap公司诚聘【区块链/后端/linux】工程师 薪水面议

### ISSUE THREAD

**Issue by kasoqian** [rebase-network/who-is-hiring#178]
## 公司/团队介绍
SuicaSwap是一家支付领域的初创公司，目前在天使轮阶段。我们推出SuicaSwap金融结算平台，降低支付门槛，致力解决于Web3的支付落地问题。项目合伙人为知名支付公司硬件负责人，项目负责人。有过大型项目的操盘经验，多起成功案例。

## 薪资福利待遇
月薪：$6,000k ~$10,000 (具体面议)

## 地点

- 工作地点：上海/远程/日本
- 联系方式：kasoqian(微信)

## 工作性质

- 是否全职：否
- 是否远程：是

## 岗位要求、职责

以下职位优先考虑的人群有
1. 有日本/台湾长期工作意愿；
2. 有区块链相关经验；
3. 有支付经验更佳。

### 区块链 工程师
1. 了解UniSwap相关源码及SDK调用；
4. 了解UniSwap升级机制与原理；
5. 了解区块链底层架构。

### Linux 工程师
1. 1年以上支付、嵌入式系统或移动设备软件开发经验。
2. 熟悉ARM架构（Core：A、R或M、MMU、SMMU、GIC、互连）。
3. 熟悉引导程序，如ARM可信固件、U-boot等。
6. 有Linux内核内存管理、电源管理（DVFS、PSCI、STR）经验者优先。
7. 有PCIE/USB2/USB3/ETH/V2L4（CSI）/UFS/DRM（DSI，DP）等HSIO驱动程序的经验者优先。

### 后端 工程师
1. 熟练掌握C++/Go/Java等1种以上语言；
2.  熟悉Linux系统，较强的解决问题能力；
3. 熟练掌握Mysql的使用和特性，熟悉常用redis的使用和特性；
5. 熟悉互联网分布式架构，良好的业务架构设计能力，熟悉行业常见的架构方案；
6. 具备交易系统或者支付系统经验者优先；

## 工作环境
目前是居家办公，后期线下办公主要集中在日本、台湾两地。
有考虑移民日本，国外生活的优先考虑。

**Comment by xiaobolei** [comment]
> ## 公司/团队介绍
> SuicaSwap是一家支付领域的初创公司，目前在天使轮阶段。我们推出SuicaSwap金融清算结算平台，降低支付门槛，致力解决于Web3的支付落地问题。项目合伙人为知名支付公司经历，硬件项目负责人有过大型项目的操盘经验，多起成功案例。
> 
> ## 薪资福利待遇
> 月薪：$6,000k ~$10,000 (具体面议)
> 
> ## 地点
> * 工作地点：上海/远程/日本
> * 联系方式：kasoqian(微信)
> 
> ## 工作性质
> * 是否全职：否
> * 是否远程：是
> 
> ## 岗位要求、职责
> 以下职位优先考虑的人群有
> 
> 1. 有日本/台湾长期工作意愿；
> 2. 有区块链相关经验；
> 3. 有支付经验更佳。
> 
> ### 区块链 工程师
> 1. 了解UniSwap相关源码及SDK调用；
> 2. 了解UniSwap升级机制与原理；
> 3. 了解区块链底层架构。
> 
> ### Linux 工程师
> 1. 1年以上支付、嵌入式系统或移动设备软件开发经验。
> 2. 熟悉ARM架构（Core：A、R或M、MMU、SMMU、GIC、互连）。
> 3. 熟悉引导程序，如ARM可信固件、U-boot等。
> 4. 有Linux内核内存管理、电源管理（DVFS、PSCI、STR）经验者优先。
> 5. 有PCIE/USB2/USB3/ETH/V2L4（CSI）/UFS/DRM（DSI，DP）等HSIO驱动程序的经验者优先。
> 
> ### 后端 工程师
> 1. 熟练掌握C++/Go/Java等1种以上语言；
> 2. 熟悉Linux系统，较强的解决问题能力；
> 3. 熟练掌握Mysql的使用和特性，熟悉常用redis的使用和特性；
> 4. 熟悉互联网分布式架构，良好的业务架构设计能力，熟悉行业常见的架构方案；
> 5. 具备交易系统或者支付系统经验者优先；
> 
> ## 工作环境
> 目前是居家办公，后期线下办公主要集中在日本、台湾两地。 有考虑移民日本，国外生活的优先考虑。
