### ISSUE TITLE
[北京] 欧科云链诚聘产品经理（实习/校招/社招）

### ISSUE THREAD

**Issue by energiediebe** [rebase-network/who-is-hiring#29]
## 公司介绍
前五的交易所，盈利水平不错，运行良好。

## 薪资福利待遇
校招1.5-2.5w 14-18薪
社招另谈
钱真的不会少
配m1+各种便利工作设备，每年给换
晚上有饭
产品不加班
社保可以选交北京或者上海。

## 地点
北京

## 工作性质

- 是否全职：是
- 是否远程：每周三天远程，两天到岗

## 岗位要求、职责
两个岗位
（1）交易所增长产品经理（校招）
岗位要求：
    ●22/23年毕业，金融&计算机背景优先，985/211本硕、海外QS前100名校经历优先。
    ●对产品有极强的好奇心和自驱力，同时具备较强的独立思考能力、判断能力。
    ●对区块链数字货币行业有强烈的兴趣和热情，了解DEFI、NFT等区块链热点优先
    ●有海外工作、学习经验优先，英文可作为工作语言优先。
岗位职责：
    ●行业研究及业务分析：通过数据分析、竞品调研、和敏锐的行业洞察（区块链+数字货币），发现业务瓶颈和增长点。
    ●增长产品设计：负责平台级增长产品的设计及相关产品优化。
    ●增长策略输出：紧跟行业动态，洞悉各国法律法规及竞争格局，输出行业研究报告，竞品分析报告。
    ●跨团队协同：与运营及商务协同，制定并推进增长策略的落地。
    ●数据基础建设：数据导向，分析用户转化全流程。

（2）链上战略产品经理
岗位要求：
    -有区块链行业经验者优先
    -有Defi、NFT相关经验者优先
    -对智能合约有相关经验者优先
    -英文流利，有海外留学或海外工作经历者优先
    -金融&计算机背景优先，985/211本硕、海外QS前100名校经历优先
    -有互联网产品经理经验者优先
岗位职责：
    -有一定的用户体验理论，能够快速发现产品中现存体验问题，并提出改进方案
    -较强的学习能力与好奇心，善于去发现行业新事物，并且能够快速学习新知识
    -业务敏感度好，善于从用户增长、业务增长角度思考问题
    -逻辑思维能力、沟通能力、推动能力强
    -强大的内驱力、责任心、大心脏，能够承担较大的工作压力和工作强度
    -对区块链行业具有浓厚兴趣

## 工作环境
还可以，就正常互联网公司水平。

简历投递请附上投哪个岗位，发送至邮箱jie.zhang@okg.com

**Comment by xrdavies** [comment]
> 区块链开发 OKEx有校招HC吗？

在issue里留言的情况建议也能通过邮件联系一下，主要是有些时候github上回复不及时
