### ISSUE TITLE
[Remote/深圳/杭州] Syrupal诚聘 资深前端工程师 薪水 25K-40K RMB

### ISSUE THREAD

**Issue by syrupal-dev** [rebase-network/who-is-hiring#381]
## 公司/团队介绍
* 我们致力于构建去中心化的链上期权交易所;
* Syrupal由前 比特大陆, MatrixPort , Top级公链项目 工程师 创立;
* 已完成数千万人民币融资。

## 薪资福利待遇

25K-40K RMB or equivalently paid in USDT

## 地点

- 工作地点：Remote/深圳/杭州
- 联系方式：hr@syrupal.com (附上GitHub)

## 工作性质

- 是否全职：是
- 是否远程：可远程(前期短期onsite)

### 岗位要求
* 热爱Web3行业，有责任心、对代码质量有追求;
* 5年以上Web前端工作经验，至少2年以上Web3行业经验(CEX or DEX更佳);
* 精通 JavaScript、HTML 和 CSS，精通**React**技术栈优先;
* 快速学习者，能够快速掌握新技术;
* 熟悉前端架构的当前趋势和最佳实践，包括性能、安全性和可用性。

### 岗位职责
* 构建去中心化的DEX页面;
* 与设计师，PM，后端工程师合作，构建优雅且响应灵敏的用户界面;

### 加分项
* 对 DeFi 感兴趣，对区块链技术和以太坊生态系统有深入的了解；
* 有良好的审美能力，对 UX/UI 设计有所理解。

## 工作环境
数字游民

**Comment by BeautifulWorld8201** [comment]
Happy New Year!
Thanks for your job post.
As a senior front-end engineer, I am very interested in this position.
This is Ming Hua Lee from Singapore and I am looking for 100% remote positions.
Please let me know if you are interested.
Thanks~
