### ISSUE TITLE
[远程] IoTeX 诚聘 高级区块链工程师（急聘）

### ISSUE THREAD

**Issue by ququzone** [rebase-network/who-is-hiring#385]
## 公司/团队介绍

IoTeX 作为硅谷开源项目成立于2017年，团队汇聚全球著名的密码学、区块链、物联网专家，是DePIN（去中心化物理基础设施网络）领域中最为重要的基础设施建设者之一。IoTeX 致力于通过 ZK 零知识证明技术，将以太坊生态系统与基于 W3bstream 的现实世界应用程序紧密结合，赋能具备万亿美元潜力市场价值的DePIN赛道。

## 薪资福利待遇

根据能力确定，高于市场水平

## 地点

- 工作地点：远程
- 联系方式：leo@iotex.io

## 工作性质

- 是否全职：是
- 是否远程：是

## 岗位职责

1. 探索Cosmos SDK/Polygon CDK项目以及开发基于上述SDK快速构建区块链开发工具链
2. 参与并推动模块化区块链的技术规范、设计、架构和实施
3. 区块链节点和相关基础设施进行性能监控和优化

## 岗位要求

1. 至少3年以上互联网或区块链相关技术开发经验，精通 Go、Rust一种或多种区块链常用开发语言
2. 精通 Cosmos SDK 或者 Polygon SDK，有1年以上该区块链开发经验
3. 精通 Socket 网络编程，精通各种数据结构和算法，对密码学、安全协议和加密算法有研究，熟悉分布式、多线程、容器技术等技术
4. 了解 HTTP/2 协议，理解 RPC 框架，具备使用 ProtoBuf/JSONRPC 的开发实践经验
5. 熟悉 Bitcoin、Ethereum、Layer2、Sharding、Cosmos、ZKP 等相关开源项目，有研究和贡献经验者优先
6. 有 LevelDB、RocksDB、PostgreSQL 等数据库开发经验
7. 具备密码学技术相关背景，有相关项目背景者优先
8. 有自研链研发经验者优先
9. 了解分布式存储并具有相关经验者优先
10. 理解各类主流的共识算法，包括不限于 PoW、PoS、DPoS、PBFT、Paxos、Raft等
11. 热爱区块链行业，有钻研区块链技术热情，学习能力强，能熟练阅读相关英文文档，具有良好的沟通能力和表达能力、团队协作精神和执行力

**Comment by Ice-Storm** [comment]
邮件地址有问题，发送后被退信
