### ISSUE TITLE
[上海] 上海分布信息科技有限公司 诚聘 智能合约开发工程师 [应届/社招均可]

### ISSUE THREAD

**Issue by qiluge** [rebase-network/who-is-hiring#43]
## 公司介绍
关于我们
 
Onchain（分布科技）是一家世界领先的区块链技术公司，致力于提供一流区块链底层技术及行业应用产品。公司成立于2016 年，在区块链技术、金融科技创新、行业解决方案等方面有着深厚技术积累。
 
公司至今已在上海、北京、新加坡、西雅图设有办公室，全球近200位员工，已获得来自复星等机构的投资，并连续4年获得KPMG评选的中国金融科技50强。
 
我们渴望更多的优秀人才与我们一起改变世界。如果你正在寻找新的挑战，快来加入我们。

## 薪资福利待遇

当前薪资上涨30%起，上不封顶，参考范围【40w~70w+】

应届生薪资对齐BAT/华为等一线大厂，参考范围【30w~50w+】

## 地点

- 工作地点：上海市杨浦区
- 联系方式：简历请投递至 wangcheng@onchain.com

## 工作性质

- 是否全职：是
- 是否远程：否

## 岗位要求、职责

岗位无工作经验要求，应届生或者已有工作经验者均可。

### 基本要求

- 计算机基础良好：熟悉操作系统原理、数据结构与算法、计算机网络
- 具有探索精神，能主动学习新的知识

### 加分项

- 熟悉区块链基本原理
- 熟悉金融领域相关知识
- 良好的数学能力

### 岗位职责

- 负责DAPP应用开发

## 工作环境

- 早上10点至晚上6点30分，午休1小时，不加班，周末双休
- 每季度部门团建+不定期公司团建+公司年会（外地旅游）
- 节假日礼品+生日礼品
- 完善的员工培养、晋升体系

**Comment by tign227** [comment]
现在还求职吗
