### ISSUE TITLE
[北京/上海] 数数科技[大数据运维工程师][Java开发工程师][数据安全专家][数据接入工程师]

### ISSUE THREAD

**Issue by tbbrave** [rebase-network/who-is-hiring#44]
# 数数科技

**简历投递： zhangdetong@thinkingdata.cn**

toB数据分析产品

北京@望京
上海@长宁

公司官网 https://www.thinkingdata.cn/

## 大数据运维工程师

1.负责线上大数据集群的日常运维、监控预警,保证集群运行的稳定性、安全性;

2.负责大数据集群的搭建和交付;

3.负责客户大数据集群后续的版本发布以及日常维护;

4.负责解决客户提出的大数据技术及运维相关的问题;

- 岗位要求：

1.熟悉大数据产品生态圈，包括但不限于HDFS、KAFKA、Hive、Zookeeper等；

2.熟悉一种或以上脚本语言(Python/Shell等),能够独立编写Shell脚本开展日常服务器的运维,熟悉Java/Go优先；

3.了解分布式平台运行的原理,并有实际部署及维护经验;

4.了解Docker、k8s的概念,运行逻辑,有实际生产经验的优先;

5.具有良好的沟通表达能力、客户服务能力。学习能力强,对新技术感兴趣。

## Java开发工程师：

1. 负责分布式大数据平台应用后端开发。
2. 理解大数据分析产品业务需求和业务价值，负责重点模块算法和功能的设计和研发。
3. 负责后台系统及相关组件的性能、效率、稳定性分析与优化。

- 岗位要求：

1. 熟悉Java web主流框架和相关组件应用和原理，熟悉设计模式、熟悉JVM，具备扎实的Java基础知识。
2. 熟悉Mysql数据库原理以及SQL优化，熟悉常见NoSQL系统。
3. 熟悉OLAP查询引擎，能够写出高性能的查询语句。
4. 具备扎实的计算机基础，熟悉分布式系统开发，熟悉大数据相关技术，熟悉云原生技术。
5. 对新技术敏感，有一定独立分析，技术研究能力，具有良好的团队合作精神。
6. 能够深刻理解业务，善于利用技术实现相关业务价值。

## 数据安全专家

1. 根据行业法律法规，建立和完善公司数据合规体系，了解相关法律法规如：《数据安全法》、《个保法》等，对公司各项规章和流程进行合规审查，提供合规改进建议并监督改进落实情况；

2. 能够独立支持数据产品及服务的合规性评审，针对复杂的业务设计逻辑能够化繁为简，厘清各环节及流程，保障数据业务开展的合规性，同时支持业务目标的实现；

3. 参与评审新业务、运营活动及其他相关事项，识别并处理公司在经营过程中发生的各类法律风险及风险事件，出具法律意见并提供切实有效的法律解决方案；

4. 牵头合规风险治理项目，输出合规标准和要求，并落实到公司业务流程中；

5. 起草、审核、修订各类商务合同，参与商务谈判，并根据实际情况形成合同模板并不断优化，定期跟进合同履行情况；

6. 日常法务支持工作（法律咨询、培训等）。

职位要求：

1. 全日制法律专业本科及以上学历，持有法律职业资格证书，985/211学校优先；

2. 互联网/IT企业或律师事务所相关工作经验，有数据安全相关经验，熟悉大数据、游戏、互联网等领域法律法规，有2B企业/数据行业相关法务支持经验优先考虑；

3. 具备较强的独立工作能力、法律分析能力和解决问题的能力；

4. 良好的沟通协调能力，具有自驱力和团队协作精神，逻辑思维缜密，乐观开朗，主动性强，执行力强。

## 数据接入工程师

1. 负责大数据产品服务端接入SDK研发。

2. 负责大数据相关接入、流式处理等组件的后端研发。

3. 负责大数据接入组件的性能、效率、稳定性分析与优化。

- 岗位要求：

1. 具备扎实的计算机基础，熟悉分布式系统开发。

2. 至少精通Go/JAVA/PHP等后端开发语言的一种，具有良好的编程开发能力。

3. 熟悉Flume/DataX/Logkit/Kafka等大数据接入技术和相关组件者优先。

4. 对新技术敏感，有较强的学习能力和解决问题的能力，乐于学习分享，有较好的沟

**Comment by liushooter** [comment]
哈喽，您好，贵司业务跟 区块链相关么？

从JD、官网上完全没看出来。

**Comment by tbbrave** [comment]
> 哈喽，您好，贵司业务跟 区块链相关么？
> 
> 从JD、官网上完全没看出来。

ok，我没有审题，不好意思。
