### ISSUE TITLE
[远程Build] metaX公司诚聘 合约工程师

### ISSUE THREAD

**Issue by tign227** [rebase-network/who-is-hiring#468]
## 公司/团队介绍

metaX是动态NFT的平台，我们将要在MINT链上构建应用，这个应用可以和推特进行连接和互动。平台提供NFT质押借贷功能，并且可以构建dNFT的市场进行交易。

## 薪资福利待遇

一起Build，一起成为cofounder，一起探索新领域。

## 地点

- 工作地点：远程
- 联系方式：tingh5370@gmail.com

## 工作性质

- 是否全职：否
- 是否远程：是

## 岗位要求、职责

我们有下面三个部分的内容：
Vault: 管理 NFT 资产，赚取收益并在扣除绩效费后分发给用户。
借贷/借款: 提供 NFT/dNFT 的 DeFi 协议，允许用户使用 NFT 进行借贷操作。
市场: 允许用户使用 dNFT 进行交易。

我们正在寻找两位合约工程师，以开发和维护NFT管理、借贷和市场交易的智能合约。我们有来自南大，北大的队员，所以希望你的背景相对较好。
## 工作环境

工作环境灵活，支持远程协作，注重团队合作和创新。

**Comment by tign227** [comment]
Build together

**Comment by passer-byzhang** [comment]
发邮件了

**Comment by tign227** [comment]
smart contract dev done
