### ISSUE TITLE
[上海/北京] 商汤科技公司诚聘 深度学习系统c++工程师

### ISSUE THREAD

**Issue by sibofeng** [rebase-network/who-is-hiring#51]
## 公司介绍

作为全球领先的人工智能软件公司商汤科技以“坚持原创，让AI引领人类进步”为使命，“以人工智能实现物理世界和数字世界的连接，促进社会生产力可持续发展，并为人们带来更好的虚实结合生活体验”为愿景，旨在持续引领人工智能前沿研究，持续打造更具拓展性更普惠的人工智能软件平台，推动经济、社会和人类的发展，并持续吸引及培养顶尖人才，共同塑造未来。

## 薪资福利待遇
20 — 50k

## 地点

- 工作地点：上海，北京
- 联系方式：fengsibo@sensetime.com

## 工作性质

- 是否全职：是
- 是否远程：否

## 岗位要求、职责
职责：
1. 负责深度学习框架功能开发
2. 研究并支持深度学习相关算法
3. 对算法的性能和精度进行挑优

要求：
1. 熟悉c++，了解软件工程，了解 python
2. 有深度学习相关经验
3. 使用过 pytorch/tensorflow 相关深度学习框架
4. 工作积极有想法，思维活跃有激情
5. 沟通良好，团队意识强

## 工作环境
1. 扁平化管理，弹性时间上下班
2. 整个组偏学术风，技术氛围浓厚

## 其他
1. 从事1～2年算法工作经验的同学投递，可以得到更多技术栈的锻炼
2. 对3～5年的c++开发，并且有异构计算项目经验的同学学，我们非常欢迎

**Comment by xrdavies** [comment]
> ## 公司介绍
> ## 薪资福利待遇
> ## 地点
> * 工作地点：
> * 联系方式：
> 
> ## 工作性质
> * 是否全职：
> * 是否远程：
> 
> ## 岗位要求、职责
> ## 工作环境

@sibofeng  大佬能填充一下职位相关的信息么？

**Comment by sibofeng** [comment]
我竟然提交个空的

> > ## 公司介绍
> > ## 薪资福利待遇
> > ## 地点
> > 
> > * 工作地点：
> > * 联系方式：
> > 
> > ## 工作性质
> > 
> > * 是否全职：
> > * 是否远程：
> > 
> > ## 岗位要求、职责
> > ## 工作环境
> 
> @sibofeng 大佬能填充一下职位相关的信息么？

我竟然提交个空的，家里的网堪忧啊

**Comment by sibofeng** [comment]
> > ## 公司介绍
> > ## 薪资福利待遇
> > ## 地点
> > 
> > * 工作地点：
> > * 联系方式：
> > 
> > ## 工作性质
> > 
> > * 是否全职：
> > * 是否远程：
> > 
> > ## 岗位要求、职责
> > ## 工作环境
> 
> @sibofeng 大佬能填充一下职位相关的信息么？

我竟然提交个空的，家里的网堪忧啊，已经更新
