### ISSUE TITLE
[远程｜黑客松] 黑客松寻找队友

### ISSUE THREAD

**Issue by tign227** [rebase-network/who-is-hiring#586]
## 公司/团队介绍
我们是黑客松团队，致力于socialfi赛道，产品已经定型，希望你可以一起加入团队中
一起参赛。我们会打造好产品然后参赛，构建我们的reputation。

## 薪资福利待遇
按照贡献度平分奖金（线上线下都会参加）

## 地点

- 工作地点：
- 联系方式：tingh5370@gmail.com

## 工作性质

- 是否全职：最好
- 是否远程：是

## 岗位要求、职责
我们目前缺少合约工程师，对能力要求不高，但希望你有良好的学习背景，因为这关系到主动性和责任感。

**Comment by vv-leo** [comment]
可以了解下这个产品吗？挺有兴趣的

**Comment by mingsheng0310** [comment]
还要人吗，全职，没有经验，学习过Solidity和区块链基础知识，在web2工作十多年

**Comment by mingsheng0310** [comment]
还要人吗，全职，没有经验，学习过Solidity和区块链基础知识，在web2工作十多年
