### ISSUE TITLE
[新加坡/可远程] Reddio 公司诚聘 Backend Engineer

### ISSUE THREAD

**Issue by Nininimonster** [rebase-network/who-is-hiring#81]
## About Reddio
Reddio is a Singapore based technology company that builds infrastructure for the blockchain, to help developers adopt blockchain technologies with the world first easy-to-use composable APIs. Enabling developers embed NFT(Non-fungible token) into their web, desktop and mobile applications with massive scalability and zero gas fee for off-chain.

We take care of the complex multi-chain and expose a global available cloud APIs that developers can interact with to build user friendly NFT applications.

We are backed by world leading investors, Arena and Paradigm, and are looking for best developers to build best tools for global developers.

## The Role 

You will be the founding team member and work closely with PM and customers to build the scaling blockchain API platform from ground up. Your team members are top developers from Meta, Amazon, Twilio, etc.

## Responsibilities
- Build reliable and trusted infrastructure and APIs needed to support multiple blockchains with the focus on Ethereum
- Work with internal and external teams to provide our customers the best possible experience developing on blockchains
- Own and lead the solution across all the software development lifecycle from conceptualisation to production deployment.
- Develop and own best practices for backend development with a focus on high throughput, high reliability, and low latency
- Identify opportunities to improve existing practices and uphold Reddio's high technical quality bar
- Write stable, high coverage test cases for launches you ship
- Debug production issues across services and multiple levels of the stack
- Be a part of a cross-functional team and collaborate with Product Managers and Architects to align on a roadmap for the platform

## What We're Looking For
- 5+ years of software development experience with cloud application development
- BS/BA degree in Computer Science
- Extensive GO language experience with multi-threaded programming
- Extensive experience with building and using REST APIs
- Ability to solve complex design, scaling, latency, or performance problems in high-throughput, low-latency systems
- Production experience with AWS, GCP or other public cloud infrastructure platforms
- Experience with production distributed systems, web applications, and micro-service architecture
- Proven track record building highly available and highly scalable systems
- Self-starter attitude and the ability to execute new ideas with autonomy
- Know how to find the right balance between perfection and shipping quickly
- Passion for blockchain technologies a big plus

## Location
This role will be based in our Singapore office and open for remote for exceptional candidate

## What you get
Competitive pay and stock options, chance to work with the most talented developers to build the world leading blockchain technology platform, and rare chance to work with a fast paced technology company.

NFT(Non-fungible token) space has been booming, GameFi has been emerging, and many more industries, like music, physical collectibles, real estate, securities, etc., are embracing NFT to revamp their business model with the benefit of NFT, like built-in authentication, liquidity of illiquid assets, fan based engagement for early product adoption, etc. However, NFT and 

We are on a mission to help such builders to disrupt the traditional way of ownership.

**Comment by veryrich** [comment]
how to contack you ?

**Comment by wartstone** [comment]
没联系方式吗
